import Head from 'next/head'
import Image from 'next/image'
import Container from './Components/Container'
import NavBar from './Components/NavBar'
import styles from '../styles/Home.module.css'
import Info from './Components/Info'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<NavBar/>

<div className=''>
<Container/>

</div>

<div>
  <div className=''>
    <Info image='https://www.svgrepo.com/show/423679/store-verified-shopping.svg' text='2'/>
    <Info image='https://www.svgrepo.com/show/423679/store-verified-shopping.svg' text='2'/>
  </div>
</div>

     <main className={styles.main}>
      
     </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
